### PR TITLE
use generics in SearchApi

### LINKED ISSUE #1134: Use generics in globalsearch
globalSearch currently returns a wildcard which always requires a cast afterwards, even though the return type is [known for each SearchScope](https://github.com/gitlab4j/gitlab4j-api/blob/e8a261a57b87ef5a9eeb44247177443c12f6c09e/src/main/java/org/gitlab4j/api/SearchApi.java#L71).

```
List<?> projects = gitLabApi.getSearchApi().globalSearch(SearchScope.PROJECTS, "text-to-search-for");
```

Ideally we would have a generic return type, based on SearchScope:

```
Pager<SearchScope> search = gitlabApi.searchApi.globalSearch(Constants.SearchScope.BLOBS, "hello")
```

[SearchScope](https://github.com/gitlab4j/gitlab4j-api/blob/e8a261a57b87ef5a9eeb44247177443c12f6c09e/src/main/java/org/gitlab4j/api/Constants.java#L733) is currently defined  as an enum which makes it impossible to use generics. We could convert it to class with static members to be able to use the same syntax and profit from generics.

```java
   // with this definition the above usage of globalSearch compiles:

    public <T> Pager<T> globalSearch(SearchScope<T> searchConstant) {
        // ...
    }

    public static class SearchScope<T> {
        private SearchScope(Class<T> clazz, String jsonName) {
        }
        
        public static final SearchScope<Project> PROJECTS = new SearchScope<>(Project.class, "projects");
        public static final SearchScope<SearchBlob> BLOBS = new SearchScope<>(SearchBlob.class, "blobs");
        
       // JsonCreator, JsonValue and ToString can be implemented using the `jsonName` field
    }

```

This would be a breaking change because code will have to be recompiled, although there should be no changes necessary on the users side.

Of course we would have to implement

### PR DESCRIPTION
**Pull request by exaV**
as proposed in https://github.com/gitlab4j/gitlab4j-api/issues/1134

Fixes #1134

### CODE REVIEW

**Comment by exaV** [comment]
It should work but I was unable to get the integration test to work. It fails with (even without my changes)
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.391 s <<< FAILURE! - in org.gitlab4j.api.TestSearchApi
org.gitlab4j.api.TestSearchApi  Time elapsed: 0.391 s  <<< ERROR!
org.gitlab4j.api.GitLabApiException: invalid_grant

```

**Comment by exaV** [comment]
Okay I was able to get the tests to work. After my latest change all tests in `TestSearchApi` are green. 

To get it to run I had to remove `seedData()` method in `org.gitlab4j.api.SetupIntegrationTestExtension#beforeAll` in my local copy of the code.

**Comment by exaV** [comment]
@jmini please review

**Comment by exaV** [comment]
@jmini Please let me know if you need me to change something to get this merged

**Comment by jmini** [comment]
Yes it is still on my TODO list to review this. Sorry for the delay.

**Comment by jmini** [comment]
Thank you very much for this contribution 🎉

**Pull request merged**
