### PR TITLE
Add erased_at attribute to Job class

### PR DESCRIPTION
**Pull request by luvarqpp**
This adds possibility to identify erased jobs. Some info and link also in javadoc.

### CODE REVIEW

**Comment by jmini** [comment]
I will rebase this branch on top of `main` to apply the change to both `5.x` and `6.x`

**Comment by luvarqpp** [comment]
Thanks, should I in a future open PR to main branch?

**Comment by jmini** [comment]
> I in a future open PR to main branch?

Yes please.
Until further decision, we maintain both versions (`5.x` and `6.x`) and I cascade the change to both branches.

**Comment by jmini** [comment]
@luvarqpp 

What I did so far:
```
git fetch origin pull/1040/head:pr_1040
git checkout pr_1040
git rebase --onto origin/main origin/6.x 
```

But I can't do `git push luvarqpp HEAD:addJobErasedAt --force`which should have updated your  branch `[feature/addJobErasedAt](https://github.com/luvarqpp/gitlab4j-api/tree/feature/addJobErasedAt)`

```
Enumerating objects: 30, done.
Counting objects: 100% (30/30), done.
Delta compression using up to 12 threads
Compressing objects: 100% (10/10), done.
Writing objects: 100% (16/16), 5.43 KiB | 927.00 KiB/s, done.
Total 16 (delta 5), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
To github.com:luvarqpp/gitlab4j-api.git
 ! [remote rejected]   HEAD -> addJobErasedAt (permission denied)
error: failed to push some refs to 'github.com:luvarqpp/gitlab4j-api.git'
```
Probably I am not allowed to do an history rewrite on your branch.

So I have pushed my commit to: branch [pr_1040](https://github.com/jmini/gitlab4j-api/tree/pr_1040).

**Comment by jmini** [comment]
`git push luvarqpp HEAD:feature/addJobErasedAt --force` worked of course.

**Comment by jmini** [comment]
@luvarqpp: I have changed the target branch in PR #1040

Be aware that your local branch `feature/addJobErasedAt` has diverged with the one on the GitHub server.

If you need to do one more change on this branch:
I recommend to use `git fetch` and `git reset --hard origin/feature/addJobErasedAt` before doing any local modifications instead of `git pull`.

**Review by jmini — APPROVED** [review]

**Comment by luvarqpp** [comment]
Thanks. I had clean repo, so git pull have worked OK and accepted your forced push:
```
➜  gitlab4j-api git:(feature/addJobErasedAt) gl
remote: Enumerating objects: 38, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 38 (delta 8), reused 17 (delta 7), pack-reused 18
Unpacking objects: 100% (38/38), 8.48 KiB | 133.00 KiB/s, done.
From github.com:luvarqpp/gitlab4j-api
 + de4de392...ebd0fb53 feature/addJobErasedAt         -> origin/feature/addJobErasedAt  (forced update)
 + 764ce784...d761a898 6.x                            -> origin/6.x  (forced update)
 + 69e4c412...7409e5e1 feature/addQueuedDuration      -> origin/feature/addQueuedDuration  (forced update)
 + 442c11ff...d0d91aa1 feature/pipelineIdInBuildEvent -> origin/feature/pipelineIdInBuildEvent  (forced update)
 * [new branch]        issue-657                      -> origin/issue-657
 * [new branch]        issue-810                      -> origin/issue-810
 * [new branch]        jabby-patch-1                  -> origin/jabby-patch-1
 + ea9042ee...608c4861 master                         -> origin/master  (forced update)
 * [new branch]        patch-1                        -> origin/patch-1
 * [new branch]        patch-2                        -> origin/patch-2
Successfully rebased and updated refs/heads/feature/addJobErasedAt.
```

Rebase on main seems work like expected. Should I do any work? If yes, what?

**Comment by jmini** [comment]
Nothing to do on your side. I have now merged the PR. Thank you for your contribution 🎉

**Pull request merged**
