### PR TITLE
Include Project in RunnersAPI.getJobs* (Issue #552)

### PR DESCRIPTION
**Pull request by ribardo0**
Hi

I added project attribute in Job class, this will work for RunnersAPI but may be confusing for JobAPI (that will never return Project Information but that uses the same class).

I also added withDuration missing method.

Olivier

### CODE REVIEW

**Comment by gmessner** [comment]
@ribardo0 Not a concern adding the ```project``` property.  Since you are down in the ```withXXX()```, there is one that needs fixed:
```
public Job allowFailureManual(Boolean allowFailure)
```
Should be:
```
public Job withAllowFailure(Boolean allowFailure)
```

Could you fix this as part of this PR?

**Comment by ribardo0** [comment]
Hi @gmessner 

OK I will do it.
Should I remove it or only create a new method and deprecate the other one (for compatibility) ?

Olivier

**Comment by gmessner** [comment]
@ribardo0 
Just rename it, I guarantee that no one is using it and with the remote chance someone is, they'll figure out.

**Comment by ribardo0** [comment]
@gmessner 
As requested I changed method name to "withAllowFailure". I also included "project" object in Job.json

**Comment by gmessner** [comment]
@ribardo0 Changes look good, merging.

Will have a release out in the next day or so.

**Pull request merged**
