### PR TITLE
Improve support for EventChange objects

### PR DESCRIPTION
**Pull request by PhilippeVienne**
Type of PR: Feature improvment
Scope: Management of Changes for webhook events

Currently the system of EventChange deserialization does not allow to handle fields like status or "id", which are use full to act on change of objects inside GitLab.

### CODE REVIEW

**Comment by gmessner** [comment]
@PhilippeVienne 
These "changes" fields you refer to are not identified in the [Webhooks](https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#overview) documentation.  Can you provide a list of events that are including the changes you are referring to and possibly some sample JSON?

I will use this as a starting point to research documentation updates for GitLab-CE.   What I am doing is trying to identify things that are either missing or incorrect in the GitLab documentation, and submit a PR to GitLab-CE with these documentation fixes.  I already have quite a few fixes ready to submit and would like to include fixes to the Webhooks documentation.

Keep in mind that the GitLab-CE and GitLab-EE documentation are the source of truth for implementing this library, and I'd like them to be in sync as much as possible.

**Comment by PhilippeVienne** [comment]
@gmessner 
Yes they are not documented because they can match to any of the fields of the data you have, for example on a Merge Request, it can be any of the fields of the MR. It is currently the goal of the "changes" field.
This is why i prefer the idea of the Map for the changes fields as it is a better match from the Webhook declaration.
I agree for the Unit test on that side, and currently there is not event unit test on webhooks nor system hooks.

**Comment by gmessner** [comment]
@PhilippeVienne 
The problem with using a map and the fields not being documented is that they can change at any time and developing integrations on non-documented items is not a good practice.  

After further research (by looking at actual events) there are lots of fields missing, these need to be added to both ```EventChanges``` and the GitLab-CE documentation:
```
      "author_id":
      "created_at"
      "description"
      "id"
      "iid"
      "source_branch"
      "source_project_id"
      "target_branch":{ 
      "target_project_id"
      "title"
      "project_id"
      "relative_position"
      "state"
```

I'd like to leave the ```other``` map for catching any new unknown fields so we could then create an integration test to look for changes that are new or undocumented and add them to both ```EventChanges``` and to the GitLab-CE documentation.

Here is what I captured from the Merge Request and Issue events.
Merge Request Event:
```
   "changes":{  
      "author_id":{  
         "previous":null,
         "current":2
      },
      "created_at":{  
         "previous":null,
         "current":"2019-05-24 16:46:29 UTC"
      },
      "description":{  
         "previous":null,
         "current":"Closes #1080"
      },
      "id":{  
         "previous":null,
         "current":2
      },
      "iid":{  
         "previous":null,
         "current":2
      },
      "source_branch":{  
         "previous":null,
         "current":"1080-this-is-a-test-issue"
      },
      "source_project_id":{  
         "previous":null,
         "current":1
      },
      "target_branch":{  
         "previous":null,
         "current":"master"
      },
      "target_project_id":{  
         "previous":null,
         "current":1
      },
      "title":{  
         "previous":null,
         "current":"WIP: Resolve \"This is a test issue\""
      },
      "updated_at":{  
         "previous":null,
         "current":"2019-05-24 16:46:29 UTC"
      },
      "total_time_spent":{  
         "previous":null,
         "current":0
      }
   }
```

Issues Event:
```
   "changes":{  
      "author_id":{  
         "previous":null,
         "current":2
      },
      "created_at":{  
         "previous":null,
         "current":"2019-05-24 16:46:03 UTC"
      },
      "description":{  
         "previous":null,
         "current":"This is a test issue"
      },
      "id":{  
         "previous":null,
         "current":1080
      },
      "iid":{  
         "previous":null,
         "current":1080
      },
      "project_id":{  
         "previous":null,
         "current":1
      },
      "relative_position":{  
         "previous":null,
         "current":1073742323
      },
      "state":{  
         "previous":null,
         "current":"opened"
      },
      "title":{  
         "previous":null,
         "current":"This is a test issue"
      },
      "updated_at":{  
         "previous":null,
         "current":"2019-05-24 16:46:03 UTC"
      },
      "total_time_spent":{  
         "previous":null,
         "current":0
      }
   }
```

**Comment by gmessner** [comment]
@PhilippeVienne 
I am going to go ahead and merge this PR.  I will then change ```EventChanges``` into an abstract class and create a ```MergeRequestChanges``` and ```IssueChanges``` subclass from that.  The Map implementation will be kept intact, and when I have time I will create an integration test that checks for new fields and reports on them.  New fields being present will not fail the test, it will just warn about them, so when in development the test can be run on the latest version of the GitLab-CE docker image and fixed if any new fields are present.

**Comment by gmessner** [comment]
@PhilippeVienne 
I have added all the change properties that are shared by both issue and merge request events to the base ```EventChanges``` abstract class and added the event type specific change properties to ```IssueChanges``` and ```MergeRequestChanges```.

After merging this PR and exploring turning ```EventChanges``` into an abstract class I have learned a lot more about this:

- Most of the so-called arbitrary properties actually only show as a change on the original creation of the issue or merge request, the never show as a change again. 

- Additionally, these so-called arbitrary changes are all available in the ```object_attributes```. Properties like ```id``` and ```iid``` fall into this category, so there is little or no reason to really keep track of them.

**Comment by gmessner** [comment]
@PhilippeVienne 
4.11.3 has been released with these changes.

**Pull request merged**
