### PR TITLE
Add group api parameters

### PR DESCRIPTION
**Pull request by simon-weimann**
- adds protected_against_pushes and full_protection_after_initial_push branch protection level
- adds prevent_sharing_groups_outside_of_hierarchy
- adds prevent_forking_outside_group

### CODE REVIEW

**Comment by jmini** [comment]
Documentation:
* https://docs.gitlab.com/ee/api/groups.html#options-for-default_branch_protection
* New group: https://docs.gitlab.com/ee/api/groups.html#new-group
* Update group: https://docs.gitlab.com/ee/api/groups.html#update-group

**Review by jmini — CHANGES_REQUESTED** [review]
It seems that those flags are also part of the response returned on group update or create.

So we should add those in `Group` and update the `group.json` as well.

**Comment by simon-weimann** [comment]
Hi @jmini,

thanks for the feedback. I have incorporated the requested changes.

**Comment by jmini** [comment]
Sorry about the failing tests on the main branch.
I made a mistake with a merge-request that I merged only partially.
This was fixed yesterday.

I have now pushed `origin/main` into your branch.

**Review by jmini — APPROVED** [review]
I will perform some tests and merge

**Pull request merged**
