### PR TITLE
Fix #411 Missing merged_at in merge request

### LINKED ISSUE #411: Missing field merged_at in MergeRequest
Check https://docs.gitlab.com/ee/api/merge_requests.html

Unfortunately, it seems that the field is not exposed in the webhook event

```
[
  {
    "id": 1,
    "iid": 1,
    "project_id": 3,
    "title": "test1",
    "description": "fixed login page css paddings",
    "state": "merged",
    "merged_by": {
      "id": 87854,
      "name": "Douwe Maan",
      "username": "DouweM",
      "state": "active",
      "avatar_url": "https://gitlab.example.com/uploads/-/system/user/avatar/87854/avatar.png",
      "web_url": "https://gitlab.com/DouweM"
    },
    "merged_at": "2018-09-07T11:16:17.520Z",
    "closed_by": null,
    "closed_at": null,
```

### PR DESCRIPTION
**Pull request by lesiak**

### CODE REVIEW

**Comment by gmessner** [comment]
@lesiak 
Missing and extra fields can be common because GitLab is constantly updating these messages.  There are actually more fields missing than ```merged_at```, following is a complete list of missing fields, could you change this MR to include all of them?
```
merged_by
merged_at
closed_by
closed_at
discussion_locked
allow_collaboration
allow_maintainer_to_push
time_stats
task_completion_status
```
The following field has been renamed:
```
merge_when_build_succeeds
    is now:
merge_when_pipeline_succeeds
```

The ```task_completion_status``` type does not exist, so it will need to be created.  

Also, please make sure to update the following test file for ```MergeRequest```:
```
src/test/resources/org/gitlab4j/api/merge-request.json
```

**Comment by lesiak** [comment]
I amended the commit with all requested fields.
I also checked that `closed_by` and `merged_by` users are listed in the MR participants endpoint, so I used existing `Participant` type to represent them.

**Comment by gmessner** [comment]
@lesiak 
Changes are spot on, thanks for making them.  Should have a release out within a day.

**Comment by gmessner** [comment]
@lesiak 
Version 4.11.18 has been released, thanks again for your contribution.

**Pull request merged**
